
import { Department, StudentPortfolio, Zone, LTC } from './types';

export const NGO_INFO = {
  name: 'YUVA PARIVARTAN',
  tagline: 'Inspiring youth to participate in the process of transformation.',
  mission: 'To provide livelihood skills to rural and urban underprivileged youth who have dropped out of school.',
  established: '1998',
  regions: 'Maharashtra, Gujarat, Karnataka, Uttar Pradesh, Bihar',
  focusAreas: ['Skill Development', 'Livelihood Training', 'Youth Empowerment'],
  regNo: 'MH/1234/NGO/98'
};

export const ZONES: Zone[] = [
  { id: 'z_a', name: 'West Zone' },
  { id: 'z_b', name: 'North Zone' },
  { id: 'z_c', name: 'South Zone' },
  { id: 'z_d', name: 'East Zone' },
];

export const LTCS: LTC[] = [
  { id: 'ltc_1', name: 'LTC 1', zoneId: 'z_a' },
  { id: 'ltc_2', name: 'LTC 2', zoneId: 'z_a' },
  { id: 'ltc_3', name: 'LTC 3', zoneId: 'z_b' },
  { id: 'ltc_4', name: 'LTC 4', zoneId: 'z_b' },
  { id: 'ltc_5', name: 'LTC 5', zoneId: 'z_c' },
  { id: 'ltc_6', name: 'LTC 6', zoneId: 'z_c' },
  { id: 'ltc_7', name: 'LTC 7', zoneId: 'z_d' },
  { id: 'ltc_8', name: 'LTC 8', zoneId: 'z_d' },
];

export const DEPARTMENTS: { name: Department; icon: string; color: string }[] = [
  { name: 'Agriculture', icon: 'fa-seedling', color: 'bg-green-600' },
  { name: 'Apparel', icon: 'fa-shirt', color: 'bg-pink-500' },
  { name: 'Automotive', icon: 'fa-car-side', color: 'bg-slate-700' },
  { name: 'Banking & Finance', icon: 'fa-piggy-bank', color: 'bg-indigo-600' },
  { name: 'Beauty & Wellness', icon: 'fa-sparkles', color: 'bg-rose-400' },
  { name: 'Construction', icon: 'fa-trowel-bricks', color: 'bg-orange-700' },
  { name: 'Electronics & IT', icon: 'fa-microchip', color: 'bg-blue-600' },
  { name: 'Food Processing', icon: 'fa-bowl-food', color: 'bg-amber-600' },
  { name: 'Handicrafts', icon: 'fa-palette', color: 'bg-purple-600' },
  { name: 'Healthcare', icon: 'fa-hand-holding-medical', color: 'bg-red-500' },
  { name: 'Hospitality', icon: 'fa-bell-concierge', color: 'bg-yellow-600' },
  { name: 'ITES', icon: 'fa-keyboard', color: 'bg-cyan-600' },
  { name: 'Management', icon: 'fa-briefcase', color: 'bg-gray-800' },
  { name: 'Retail', icon: 'fa-shop', color: 'bg-emerald-600' },
  { name: 'Telecom', icon: 'fa-tower-cell', color: 'bg-blue-400' },
];

export const INITIAL_DATA: StudentPortfolio[] = [
  {
    id: 'yp-101',
    fullName: 'Aarav Patel',
    fatherName: 'Rajesh Patel',
    dob: '2000-05-15',
    gender: 'Male',
    mobile: '9876543210',
    email: 'aarav.patel@example.com',
    village: 'Vadal',
    district: 'Junagadh',
    state: 'Gujarat',
    preferredLocation: 'Ahmedabad',
    zoneId: 'z_a',
    ltcId: 'ltc_1',
    department: 'Agriculture',
    courseTitle: 'Goat Farming',
    duration: '20 Hours',
    educationLevel: 'Graduate',
    instituteName: 'Junagadh Agri Univ',
    passingYear: '2022',
    studiedMaths: true,
    studiedEnglish: true,
    studiedComputers: true,
    basicComputerKnowledge: true,
    knowsTyping: true,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Word', 'MS Excel (Basic)'],
    typingSpeed: '20–30',
    languages: { local: true, hindi: true, english: { read: true, write: true, speak: false } },
    experience: 'Farm work',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Looking to modernize goat farming in my district.',
    skills: [{ name: 'Livestock Care', level: 'Intermediate' }],
    joinedDate: '2024-01-10',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aarav',
    status: 'Approved',
    lastUpdated: '2024-03-25'
  },
  {
    id: 'yp-102',
    fullName: 'Meera Deshmukh',
    fatherName: 'Sanjay Deshmukh',
    dob: '2003-08-22',
    gender: 'Female',
    mobile: '9123456780',
    email: 'meera.d@example.com',
    village: 'Wada',
    district: 'Palghar',
    state: 'Maharashtra',
    preferredLocation: 'Mumbai',
    zoneId: 'z_a',
    ltcId: 'ltc_2',
    department: 'Healthcare',
    courseTitle: 'Nursing Assistant',
    duration: '420 Hours',
    educationLevel: '12th',
    instituteName: 'Rural Health Center',
    passingYear: '2021',
    studiedMaths: true,
    studiedEnglish: true,
    studiedComputers: false,
    basicComputerKnowledge: true,
    knowsTyping: false,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Word'],
    typingSpeed: 'Below 20 WPM',
    languages: { local: true, hindi: true, english: { read: true, write: true, speak: true } },
    experience: 'None',
    willingToLearn: true,
    availability: 'Shift work',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Passionate about elderly care and health support.',
    skills: [{ name: 'Patient Support', level: 'Beginner' }],
    joinedDate: '2024-02-05',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Meera',
    status: 'Approved',
    lastUpdated: '2024-03-22'
  },
  {
    id: 'yp-103',
    fullName: 'Rahul Singh',
    fatherName: 'Deepak Singh',
    dob: '1999-11-10',
    gender: 'Male',
    mobile: '9822334455',
    email: 'rahul.s@example.com',
    village: 'Khurja',
    district: 'Bulandshahr',
    state: 'Uttar Pradesh',
    preferredLocation: 'Noida',
    zoneId: 'z_b',
    ltcId: 'ltc_3',
    department: 'ITES',
    courseTitle: 'Data Entry',
    duration: '120 Hours',
    educationLevel: 'ITI',
    instituteName: 'Sikri ITI',
    passingYear: '2020',
    studiedMaths: true,
    studiedEnglish: true,
    studiedComputers: true,
    basicComputerKnowledge: true,
    knowsTyping: true,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Excel (Basic)', 'Data Entry Software'],
    typingSpeed: '30+',
    languages: { local: true, hindi: true, english: { read: true, write: true, speak: false } },
    experience: 'Office helper',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Keen on supporting back-office operations with high efficiency.',
    skills: [{ name: 'Fast Typing', level: 'Advanced' }],
    joinedDate: '2024-03-01',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RahulS',
    status: 'Approved',
    lastUpdated: '2024-03-28'
  }
];
