
import { Department, Zone, LTC, DashboardConfig, StudentPortfolio } from './types';

export const NGO_INFO = {
  name: 'YUVA PARIVARTAN',
  tagline: 'Inspiring youth to participate in the process of transformation.',
  mission: 'To provide livelihood skills to rural and urban underprivileged youth who have dropped out of school.',
  established: '1998',
  regions: 'Maharashtra, Gujarat, Karnataka, Uttar Pradesh, Bihar',
  focusAreas: ['Skill Development', 'Livelihood Training', 'Youth Empowerment'],
  regNo: 'MH/1234/NGO/98',
  email: 'info@yuvaparivartan.org',
  phones: ['+91 8828170103', '+91 8828059189']
};

export const INITIAL_DASHBOARD_CONFIG: DashboardConfig = {
  showJobReadiness: true,
  showRegionalImpact: true,
  showDiversity: true,
  showLtcDistribution: true,
  customTitle: 'Yuva Parivartan Impact'
};

export const ZONES: Zone[] = [
  { id: 'z_a', name: 'West Zone' },
  { id: 'z_b', name: 'North Zone' },
];

export const LTCS: LTC[] = [
  { id: 'ltc_1', name: 'Khurja Center', zoneId: 'z_b' },
  { id: 'ltc_2', name: 'Mumbai Hub', zoneId: 'z_a' },
];

export const DEPARTMENTS: Department[] = [
  { id: 'd_1', name: 'Agriculture', icon: 'fa-seedling', color: 'bg-green-600' },
  { id: 'd_2', name: 'Healthcare', icon: 'fa-hand-holding-medical', color: 'bg-red-500' },
  { id: 'd_3', name: 'Electronics & IT', icon: 'fa-microchip', color: 'bg-blue-600' },
  { id: 'd_4', name: 'Apparel', icon: 'fa-shirt', color: 'bg-pink-500' },
];

export const INITIAL_STUDENTS: StudentPortfolio[] = [
  {
    id: 'yp-mock-1',
    fullName: 'Arjun Mehra',
    fatherName: 'Suresh Mehra',
    dob: '2001-04-12',
    gender: 'Male',
    mobile: '9822113344',
    email: 'arjun.m@example.com',
    village: 'Vadal',
    district: 'Junagadh',
    state: 'Gujarat',
    preferredLocation: 'Ahmedabad',
    zoneId: 'z_a',
    ltcId: 'ltc_2',
    departmentId: 'd_1',
    courseTitle: 'Organic Farming',
    duration: '3 Months',
    educationLevel: '12th',
    instituteName: 'Junagadh Rural School',
    passingYear: '2019',
    studiedMaths: true,
    studiedEnglish: false,
    studiedComputers: false,
    basicComputerKnowledge: true,
    knowsTyping: false,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Word'],
    typingSpeed: 'Below 20 WPM',
    languages: { local: true, hindi: true, english: { read: true, write: false, speak: false } },
    experience: 'Farm work',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Looking to bring modern organic techniques to my village farms.',
    skills: [{ name: 'Soil Testing', level: 'Intermediate' }],
    joinedDate: '2024-01-15',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun',
    status: 'Approved',
    lastUpdated: '2024-03-01'
  },
  {
    id: 'yp-mock-2',
    fullName: 'Priya Sharma',
    fatherName: 'Rajesh Sharma',
    dob: '2003-09-20',
    gender: 'Female',
    mobile: '9122334455',
    email: 'priya.s@example.com',
    village: 'Khurja Khas',
    district: 'Bulandshahr',
    state: 'Uttar Pradesh',
    preferredLocation: 'Noida',
    zoneId: 'z_b',
    ltcId: 'ltc_1',
    departmentId: 'd_2',
    courseTitle: 'Nursing Assistant',
    duration: '6 Months',
    educationLevel: 'Graduate',
    instituteName: 'District College',
    passingYear: '2022',
    studiedMaths: true,
    studiedEnglish: true,
    studiedComputers: true,
    basicComputerKnowledge: true,
    knowsTyping: true,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Excel (Basic)', 'MS Word'],
    typingSpeed: '30+',
    languages: { local: true, hindi: true, english: { read: true, write: true, speak: true } },
    experience: 'None',
    willingToLearn: true,
    availability: 'Shift work',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Passionate about patient care and clinical assistance.',
    skills: [{ name: 'First Aid', level: 'Advanced' }],
    joinedDate: '2024-02-10',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    status: 'Approved',
    lastUpdated: '2024-03-05'
  },
  {
    id: 'yp-mock-3',
    fullName: 'Rohan Deshmukh',
    fatherName: 'Anil Deshmukh',
    dob: '2000-01-05',
    gender: 'Male',
    mobile: '9988776655',
    email: 'rohan.d@example.com',
    village: 'Wada',
    district: 'Palghar',
    state: 'Maharashtra',
    preferredLocation: 'Mumbai',
    zoneId: 'z_a',
    ltcId: 'ltc_2',
    departmentId: 'd_3',
    courseTitle: 'Data Entry Operations',
    duration: '2 Months',
    educationLevel: 'ITI',
    instituteName: 'Palghar ITI',
    passingYear: '2021',
    studiedMaths: true,
    studiedEnglish: true,
    studiedComputers: true,
    basicComputerKnowledge: true,
    knowsTyping: true,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Excel (Basic)', 'Data Entry Software'],
    typingSpeed: '20–30',
    languages: { local: true, hindi: true, english: { read: true, write: true, speak: false } },
    experience: 'Shop helper',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: false, educationCertificate: true },
    bio: 'Eager to work in back-office operations and improve my typing speed.',
    skills: [{ name: 'Excel Mastery', level: 'Intermediate' }],
    joinedDate: '2024-03-01',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rohan',
    status: 'Pending',
    lastUpdated: '2024-03-01'
  },
  {
    id: 'yp-mock-4',
    fullName: 'Sana Khan',
    fatherName: 'Irfan Khan',
    dob: '2002-11-30',
    gender: 'Female',
    mobile: '8877665544',
    email: 'sana.k@example.com',
    village: 'Sikri',
    district: 'Bulandshahr',
    state: 'Uttar Pradesh',
    preferredLocation: 'Delhi',
    zoneId: 'z_b',
    ltcId: 'ltc_1',
    departmentId: 'd_4',
    courseTitle: 'Apparel Design',
    duration: '4 Months',
    educationLevel: '10th',
    instituteName: 'Sikri Secondary',
    passingYear: '2018',
    studiedMaths: false,
    studiedEnglish: true,
    studiedComputers: false,
    basicComputerKnowledge: false,
    knowsTyping: false,
    knowsMouseKeyboard: false,
    knowsFileHandling: false,
    softwareKnown: [],
    typingSpeed: 'Below 20 WPM',
    languages: { local: true, hindi: true, english: { read: false, write: false, speak: false } },
    experience: 'None',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Skilled in traditional embroidery and looking to learn modern machine stitching.',
    skills: [{ name: 'Embroidery', level: 'Advanced' }],
    joinedDate: '2024-03-12',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sana',
    status: 'Approved',
    lastUpdated: '2024-03-15'
  },
  {
    id: 'yp-mock-5',
    fullName: 'Deepak Kumar',
    fatherName: 'Omprakash Kumar',
    dob: '1999-05-25',
    gender: 'Male',
    mobile: '7766554433',
    email: 'deepak.k@example.com',
    village: 'Ahar',
    district: 'Bulandshahr',
    state: 'Uttar Pradesh',
    preferredLocation: 'Noida',
    zoneId: 'z_b',
    ltcId: 'ltc_1',
    departmentId: 'd_1',
    courseTitle: 'Tractor Mechanic',
    duration: '3 Months',
    educationLevel: 'ITI',
    instituteName: 'Ahar Technical',
    passingYear: '2020',
    studiedMaths: true,
    studiedEnglish: false,
    studiedComputers: false,
    basicComputerKnowledge: true,
    knowsTyping: false,
    knowsMouseKeyboard: true,
    knowsFileHandling: false,
    softwareKnown: [],
    typingSpeed: 'Below 20 WPM',
    languages: { local: true, hindi: true, english: { read: true, write: false, speak: false } },
    experience: 'None',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Mechanical enthusiast looking to support rural agriculture with repair services.',
    skills: [{ name: 'Engine Repair', level: 'Intermediate' }],
    joinedDate: '2024-01-20',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Deepak',
    status: 'Approved',
    lastUpdated: '2024-03-10'
  },
  {
    id: 'yp-mock-6',
    fullName: 'Anjali Patil',
    fatherName: 'Sanjay Patil',
    dob: '2004-03-14',
    gender: 'Female',
    mobile: '9922883311',
    email: 'anjali.p@example.com',
    village: 'Hadapsar',
    district: 'Pune',
    state: 'Maharashtra',
    preferredLocation: 'Pune',
    zoneId: 'z_a',
    ltcId: 'ltc_2',
    departmentId: 'd_3',
    courseTitle: 'IT Literacy',
    duration: '3 Months',
    educationLevel: '12th',
    instituteName: 'Pune High School',
    passingYear: '2022',
    studiedMaths: true,
    studiedEnglish: true,
    studiedComputers: true,
    basicComputerKnowledge: true,
    knowsTyping: true,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Word', 'MS Excel (Basic)', 'MS PowerPoint'],
    typingSpeed: '30+',
    languages: { local: true, hindi: true, english: { read: true, write: true, speak: true } },
    experience: 'None',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Fluent in English and Computers, ready for a front-desk or data role.',
    skills: [{ name: 'Presentation', level: 'Intermediate' }],
    joinedDate: '2024-02-28',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anjali',
    status: 'Approved',
    lastUpdated: '2024-03-20'
  },
  {
    id: 'yp-mock-7',
    fullName: 'Karan Singh',
    fatherName: 'Vikram Singh',
    dob: '1998-12-12',
    gender: 'Male',
    mobile: '9900112233',
    email: 'karan.s@example.com',
    village: 'Debai',
    district: 'Bulandshahr',
    state: 'Uttar Pradesh',
    preferredLocation: 'Gurgaon',
    zoneId: 'z_b',
    ltcId: 'ltc_1',
    departmentId: 'd_3',
    courseTitle: 'BPO Operations',
    duration: '2 Months',
    educationLevel: 'Graduate',
    instituteName: 'UP State Univ',
    passingYear: '2020',
    studiedMaths: true,
    studiedEnglish: true,
    studiedComputers: true,
    basicComputerKnowledge: true,
    knowsTyping: true,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Word', 'CRM Basics'],
    typingSpeed: '30+',
    languages: { local: true, hindi: true, english: { read: true, write: true, speak: true } },
    experience: 'Office helper',
    willingToLearn: true,
    availability: 'Shift work',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Graduate with strong communication skills and BPO training.',
    skills: [{ name: 'Customer Service', level: 'Advanced' }],
    joinedDate: '2024-03-05',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Karan',
    status: 'Approved',
    lastUpdated: '2024-03-25'
  },
  {
    id: 'yp-mock-8',
    fullName: 'Meera Nair',
    fatherName: 'Gopal Nair',
    dob: '2001-07-08',
    gender: 'Female',
    mobile: '8811229900',
    email: 'meera.n@example.com',
    village: 'Vashi',
    district: 'Navi Mumbai',
    state: 'Maharashtra',
    preferredLocation: 'Mumbai',
    zoneId: 'z_a',
    ltcId: 'ltc_2',
    departmentId: 'd_2',
    courseTitle: 'Lab Technician Asst',
    duration: '6 Months',
    educationLevel: '12th',
    instituteName: 'Navi Mumbai School',
    passingYear: '2019',
    studiedMaths: true,
    studiedEnglish: true,
    studiedComputers: false,
    basicComputerKnowledge: true,
    knowsTyping: false,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Word'],
    typingSpeed: 'Below 20 WPM',
    languages: { local: true, hindi: true, english: { read: true, write: true, speak: false } },
    experience: 'None',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Dedicated learner focused on healthcare laboratory excellence.',
    skills: [{ name: 'Lab Safety', level: 'Intermediate' }],
    joinedDate: '2024-01-10',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MeeraN',
    status: 'Approved',
    lastUpdated: '2024-02-15'
  },
  {
    id: 'yp-mock-9',
    fullName: 'Sahil Shaikh',
    fatherName: 'Yusuf Shaikh',
    dob: '2002-02-14',
    gender: 'Male',
    mobile: '7733445566',
    email: 'sahil.s@example.com',
    village: 'Bhiwandi',
    district: 'Thane',
    state: 'Maharashtra',
    preferredLocation: 'Thane',
    zoneId: 'z_a',
    ltcId: 'ltc_2',
    departmentId: 'd_4',
    courseTitle: 'Industrial Tailoring',
    duration: '3 Months',
    educationLevel: '10th',
    instituteName: 'Bhiwandi Academy',
    passingYear: '2018',
    studiedMaths: false,
    studiedEnglish: false,
    studiedComputers: false,
    basicComputerKnowledge: false,
    knowsTyping: false,
    knowsMouseKeyboard: false,
    knowsFileHandling: false,
    softwareKnown: [],
    typingSpeed: 'Below 20 WPM',
    languages: { local: true, hindi: true, english: { read: false, write: false, speak: false } },
    experience: 'Shop helper',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: false, educationCertificate: false },
    bio: 'Hardworking youth looking to enter the garment industry.',
    skills: [{ name: 'Machine Operation', level: 'Beginner' }],
    joinedDate: '2024-03-20',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sahil',
    status: 'Pending',
    lastUpdated: '2024-03-20'
  },
  {
    id: 'yp-mock-10',
    fullName: 'Kavita Jadhav',
    fatherName: 'Prakash Jadhav',
    dob: '2003-05-05',
    gender: 'Female',
    mobile: '9944556677',
    email: 'kavita.j@example.com',
    village: 'Karjat',
    district: 'Raigad',
    state: 'Maharashtra',
    preferredLocation: 'Navi Mumbai',
    zoneId: 'z_a',
    ltcId: 'ltc_2',
    departmentId: 'd_1',
    courseTitle: 'Poultry Management',
    duration: '2 Months',
    educationLevel: '12th',
    instituteName: 'Karjat Agri School',
    passingYear: '2021',
    studiedMaths: true,
    studiedEnglish: false,
    studiedComputers: false,
    basicComputerKnowledge: true,
    knowsTyping: false,
    knowsMouseKeyboard: true,
    knowsFileHandling: true,
    softwareKnown: ['MS Word'],
    typingSpeed: 'Below 20 WPM',
    languages: { local: true, hindi: true, english: { read: true, write: false, speak: false } },
    experience: 'Farm work',
    willingToLearn: true,
    availability: 'Full-time',
    documents: { aadhaar: true, bankAccount: true, educationCertificate: true },
    bio: 'Passionate about livestock management and scaling small poultry farms.',
    skills: [{ name: 'Bird Vaccination', level: 'Intermediate' }],
    joinedDate: '2024-02-01',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavita',
    status: 'Approved',
    lastUpdated: '2024-03-10'
  }
];
